### ISSUE TITLE
T450s issues

### ISSUE THREAD

**Issue by photognat** [tluck/OS-X-Voodoo-PS2-Controller#8]
Hello,

I've been using this kext for my T450s and it works better than all the other ones I tried, thanks for maintaining this.

I do have two small problems though. The main one is that the middle click doesn't work a lot of the time. For scrolling it works fine but it takes a few clicks to close a browser tab. I think it's picking up tiny movements from my finger on the trackpoint and it thinks I'm trying to scroll instead of middle click. Is there a setting in Info.plist to increase the movement threshold required before it registers a middle click as a scroll instead of a click?

The other problem is that the trackpoint is only recognized about 1/2 of the times I boot the system. Sleep doesn't work (due to USB wifi) so I have to boot almost every day and half the time the trackpad will work but not the trackpoint so I have to restart the system. Have you seen that before or is that a kext cache loading issue? My kext is in S/L/E, it didn't seem to work in /EFI/CLOVER/kexts.

My system has a full custom DSDT/SSDT, using the latest 1.8.25 version and OSX 10.12.3. Thanks!

**Comment by tluck** [comment]
sorry for the delay in response.

1) i choose to make the middle button a cut/paste tool (say in a terminal) - not very many apps seem to recognize this cut/paste thing. When the middle button is pressed it immediately looks for red button movement and this is a scroll event. so if you are moving the red button it disables cut/paste. 

2) i have not seen this issue on the T460 - i had lots of issues on my older T420 like this but since i changes the initialization it went away. i don't understand why it is random. sorry.

there are other init sequences to try for you.
// tjl - reset seems to work best with ThinkPad
#define FULL_HW_RESET
//#define SET_STREAM_MODE
//#define UNDOCUMENTED_INIT_SEQUENCE_PRE
#define UNDOCUMENTED_INIT_SEQUENCE_POST
